name: 'check if test'
description: 'check run'
inputs:
  conclusion:  
    description: 'of the test in question'
    required: true
    default: 'failure'
  author:
    description: 'name'
    required: true
    default: 'none'
  myToken:
    description: 'github token'
    required: true
    default: 'none'
  pull_request_head_sha:
    description: 'head_sha'
    required: true
    default: 'none'
  owner:
    description: 'of the repo the check run is on'
    required: true
    default: 'none'
  repo:
    description: 'that the check run was run on'
    required: true 
    default: 'none'
  testName:
    description: 'of the check run'
    required: true
    default: 'none'
  testNameToCheckAgainst:
    description: 'of the check run'
    required: true
    default: 'none'
outputs:
  checkRun:
    description: 'of this test'
runs:
  using: 'node12'
  main: 'index.js'