name: actions-sample-test
on:
  push:
    branches:
    - main
  pull_request:
  pull_request_target:
    types: [labeled]
  schedule:
  - cron:  '0 2 * * *'
jobs:
  actions-sample-test:
    if: ${{ github.event.action != 'labeled' || github.event.label.name == 'actions:force-run' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.sha}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - uses: 'google-github-actions/auth@v0.6.0'
      with:
        workload_identity_provider: 'projects/1046198160504/locations/global/workloadIdentityPools/nodejs-libs-pool/providers/nodejs-libs-provider'
        service_account: 'kokoro-system-test@long-door-651.iam.gserviceaccount.com'
        token_format: access_token
        access_token_lifetime: 600s
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm install
    - run: npm link ../
      working-directory: samples
    - run: npm install
      working-directory: samples
    - run: npm run samples-test || cat ./samples/test_output_sponge_log.xml && false
      env:
        GCLOUD_PROJECT: long-door-651
        DEBUG: mocha*
        MOCHA_REPORTER_OUTPUT: test_output_sponge_log.xml
        MOCHA_REPORTER: xunit
    - if: ${{ github.event.action == 'labeled' && github.event.label.name == 'actions:force-run' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          try {
            await github.rest.issues.removeLabel({
              name: 'actions:force-run',
              owner: 'googleapis',
              repo: 'nodejs-secret-manager',
              issue_number: context.payload.pull_request.number
            });
          } catch (e) {
            if (!e.message.includes('Label does not exist')) {
              throw e;
            }
          }
    - if: ${{ github.event_name == 'schedule'}}
      run: |
        curl https://github.com/googleapis/repo-automation-bots/releases/download/flakybot-1.1.0/flakybot -o flakybot -s -L
        chmod +x ./flakybot
        ./flakybot --repo ${{github.repository}} --commit_hash ${{github.sha}} --build_url https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
